config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :areas, except: [:show, :destroy]
    resources :spots, except: [:destroy, :show]
    resources :genres, except: [:show, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end
  scope module: :public do
    devise_for :users
    root to: 'homes#top'
    get "/homes/spot" => "homes#spot"
    post "/homes/guest_sign_in" => "homes#new_guest", as: "guest_sign_in"
    get "/users/withdrawal_confirm" => "users#withdrawal_confirm", as: "withdrawal_confirm"
    resources :users, only: [:show, :edit, :update, :destroy] do
      resource :relationships, only: [:show, :create, :destroy]
    end
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :spots

  validates :name, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :user_id, uniqueness: { scope: :post_id }

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :post_genres
  has_many :genres, through: :post_genres

  validates :name, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :spot
  has_many :post_genres
  has_many :genres, through: :post_genres
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_many_attached :images

  validates :name, presence: true
  validates :user_id, presence: true
  validates :introduction, presence: true
  validates :images, presence: true
  validates :spot_id, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.favorited_order
    self.joins(:favorites).group("favorites.post_id").order("count(favorites.post_id) desc")
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :comment, presence: true

end

app/models/post_genre.rb
class PostGenre < ApplicationRecord

  belongs_to :post
  belongs_to :genre

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :area
  has_many :posts

  validates :name, presence: true
  validates :area_id, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :follower_relationships, foreign_key: :followed_id, class_name: "Relationship"
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :followed_relationships, foreign_key: :follower_id, class_name: "Relationship"
  has_many :followeds, through: :followed_relationships, source: :followed

  has_one_attached :profile_image

  validates :name, presence: true

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "defaullt-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(gravity: :center, resize: "100x100", crop: "70x70+0+0").processed
  end

  def followeds?(user)
    followeds.include?(user)
  end

end

app/controllers/admin/spots_controller.rb
class Admin::SpotsController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!

  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    if @spot.save
      flash[:notice] = "スポット作成完了！"
      redirect_to admin_spots_path
    else
      render :new
    end
  end

  def index
    @spots = Spot.all
  end

  def edit
    @spot = Spot.find(params[:id])
    @areas = Area.all
  end

  def update
    @spot = Spot.find(params[:id])
    if @spot.update(spot_params)
      flash[:notice] = "スポット編集完了！"
      redirect_to admin_spots_path
    else
      render :edit
    end
  end

  private

  def spot_params
    params.require(:spot).permit(:name, :area_id, :address, :latitude, :longitude)
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    if @area.save
      flash[:notice] = "You have created area successfully."
      redirect_to areas_path
    else
      render :new
    end
  end

  def index
    @areas = Area.all
  end

  def edit
    @area = Area.find(params[:id])
  end

  def update
    @area = Area.find(params[:id])
    if @area.update(area_params)
      flash[:notice] = "You have updated area successfully."
      redirect_to areas_path
    else
      render :edit
    end
  end

  private

  def area_params
    params.require(:area).permit(:name)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def spot
    @spots = Spot.all
    @spots_json = @spots.map { |o| spot_to_hash(o) }.to_json
  end

  def area
    @areas = Area.all
  end

  def genre
    @genres = Genre.all
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました"
  end

  private

  def spot_to_hash(spot)
    { id: spot.id,
      name: spot.name,
      lat: spot.latitude,
      lng: spot.longitude }
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  def new
    @spot = Spot.new
  end

  def create
    @spot = Spot.new(spot_params)
    if @spot.save
      flash[:notice] = "You have created spot successfully."
      redirect_to spots_path
    else
      render :new
    end
  end

  def index
    @spots = Spot.all
  end

  def edit
    @spot = Spot.find(params[:id])
    @areas = Area.all
  end

  def update
    @spot = Spot.find(params[:id])
    if @spot.update(spot_params)
      flash[:notice] = "You have updated spot successfully."
      redirect_to spots_path
    else
      render :edit
    end
  end

  private

  def spot_params
    params.require(:spot).permit(:name, :area_id, :address, :latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_genres_helper.rb
module PostGenresHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/spots/edit.html.erb
<div class = "row">
  <div class = "col-md-10 offset-md-2">

    <h4>スポット編集</h4>

    <%= form_with model: @spot, url: spot_path, method: :patch do |f| %>
      <div class = "field mb-3">
        <%= f.label :"スポット名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div data-controller = "google-map--form mb-3">
        <%= f.label :"キーワードで探す" %><br>
        <%= f.search_field :keyword, data: { google_map__form_target: "keyword" } %><br>

        <%= f.label :"緯度" %>
        <%= f.number_field :latitude, data: { google_map__form_target: "latitude" }, tabindex: -1, readonly: true, class: "looks_disable" %>
        <%= f.label :"経度" %>
        <%= f.number_field :longitude, data: { google_map__form_target: "longitude" }, tabindex: -1, readonly: true, class: "looks_disable"%><br>

        <div data-google-map--form-target="map" style="height:30vh;max-width:300px;"></div>

        <%= f.label :"address" %>
        <%= f.text_field :address, list: "address_list", data: { google_map__form_target: "address" } %><br>
        <datalist id = "address_list" data-google-map--form-target = "addressList" ></datalist>
      </div>

      <div class = "select-field mb-3">
        <%= f.label :"所属エリア選択" %>
        <%= f.collection_select :area_id, @areas, :id, :name, include_blank: "選択して下さい" %>
      </div>

      <div class = "actions mb-3">
        <%= f.submit "編集完了", class: "btn btn-success" %>
      </div>
    <% end %>

    <%= link_to spots_path do %>
      戻る
    <% end %>

  </div>
</div>

app/views/spots/index.html.erb
<div class = "row justify-content-center">
  <div class = "col-md-12">

    <%= link_to new_spot_path do %>
      <p>スポット作成</p>
    <% end %>

    <h4>スポット一覧</h4>

    <table class = "spot-table">
      <thead>
        <tr>
          <th>スポットID</th>
          <th>スポット名</th>
          <th>エリア</th>
          <th>住所</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @spots.each do |spot| %>
          <tr>
            <td><%= spot.id %></td>
            <td><%= spot.name %></td>
            <td><%= spot.area.name %></td>
            <td><%= spot.address %></td>
            <td>
              <%= link_to edit_spot_path(spot.id) do %>
                編集する
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/spots/new.html.erb
<div class = "row">
  <div class = "col-md-8 mx-auto">

    <h4>スポット作成フォーム</h4>

    <%= form_with model: @spot, url: spots_path, method: :post do |f| %>
      <div class = "field mb-3">
        <%= f.label :"スポット名" %><br>
        <%= f.text_field :name, class: "form-control", placeholder: "スポット名を入力してください" %>
      </div>

      <div data-controller = "google-map--form mb-3">
        <%= f.label :"キーワードで探す" %><br>
        <%= f.search_field :keyword, data: { google_map__form_target: "keyword" } %><br>

        <%= f.label :"緯度" %>
        <%= f.number_field :latitude, data: { google_map__form_target: "latitude" }, tabindex: -1, readonly: true, class: "looks_disable" %>
        <%= f.label :"経度" %>
        <%= f.number_field :longitude, data: { google_map__form_target: "longitude" }, tabindex: -1, readonly: true, class: "looks_disable"%><br>

        <div data-google-map--form-target="map" style="height:30vh;max-width:50%;"></div>

        <%= f.label :"address" %>
        <%= f.text_field :address, list: "address_list", data: { google_map__form_target: "address" } %><br>
        <datalist id = "address_list" data-google-map--form-target = "addressList" ></datalist>
      </div>

      <div class = "select-field mb-3">
        <%= f.label :"所属エリア選択" %><br>
        <%= f.collection_select :area_id, Area.all, :id, :name, include_blank: "選択して下さい" %>
      </div>

      <div class = "actions mb-3">
        <%= f.submit "作成する", class: "btn btn-success" %>
      </div>
    <% end %>

    <%= link_to spots_path do %>
      <p>スポット一覧</p>
    <% end %>

  </div>
</div>