config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :areas, except: [:show, :destroy]
    resources :spots, except: [:destroy, :show]
    resources :genres, except: [:show, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end
  scope module: :public do
    devise_for :users
    root to: 'homes#top'
    get "/homes/spot" => "homes#spot"
    post "/homes/guest_sign_in" => "homes#new_guest", as: "guest_sign_in"
    get "/users/withdrawal_confirm" => "users#withdrawal_confirm", as: "withdrawal_confirm"
    resources :users, only: [:show, :edit, :update, :destroy] do
      resource :relationships, only: [:show, :create, :destroy]
    end
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :spots

  validates :name, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :user_id, uniqueness: { scope: :post_id }

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :post_genres
  has_many :genres, through: :post_genres

  validates :name, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :spot
  has_many :post_genres
  has_many :genres, through: :post_genres
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_many_attached :images

  validates :name, presence: true
  validates :user_id, presence: true
  validates :introduction, presence: true
  validates :images, presence: true
  validates :spot_id, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.favorited_order
    self.joins(:favorites).group("favorites.post_id").order("count(favorites.post_id) desc")
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :comment, presence: true

end

app/models/post_genre.rb
class PostGenre < ApplicationRecord

  belongs_to :post
  belongs_to :genre

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :area
  has_many :posts

  validates :name, presence: true
  validates :area_id, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :follower_relationships, foreign_key: :followed_id, class_name: "Relationship"
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :followed_relationships, foreign_key: :follower_id, class_name: "Relationship"
  has_many :followeds, through: :followed_relationships, source: :followed

  has_one_attached :profile_image

  validates :name, presence: true

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "defaullt-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(gravity: :center, resize: "100x100", crop: "70x70+0+0").processed
  end

  def followeds?(user)
    followeds.include?(user)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンル作成完了！"
      redirect_to admin_genres_path
    else
      render :new
    end
  end

  def index
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンル編集完了！"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    if @area.save
      flash[:notice] = "You have created area successfully."
      redirect_to areas_path
    else
      render :new
    end
  end

  def index
    @areas = Area.all
  end

  def edit
    @area = Area.find(params[:id])
  end

  def update
    @area = Area.find(params[:id])
    if @area.update(area_params)
      flash[:notice] = "You have updated area successfully."
      redirect_to areas_path
    else
      render :edit
    end
  end

  private

  def area_params
    params.require(:area).permit(:name)
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "You have created genre successfully."
      redirect_to genres_path
    else
      render :new
    end
  end

  def index
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "You have updated genre successfully."
      redirect_to genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def spot
    @spots = Spot.all
    @spots_json = @spots.map { |o| spot_to_hash(o) }.to_json
  end

  def area
    @areas = Area.all
  end

  def genre
    @genres = Genre.all
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました"
  end

  private

  def spot_to_hash(spot)
    { id: spot.id,
      name: spot.name,
      lat: spot.latitude,
      lng: spot.longitude }
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_genres_helper.rb
module PostGenresHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/genres/edit.html.erb
<div class="row">
  <div class="col-md-10 col-12 offset-md-2">

    <% if @genre.errors.any? %>
      <div class="errors-message mx-auto">
        <%= @genre.errors.count %>件のエラーが発生しました
        <ul>
          <% @genre.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h4>ジャンル編集</h4>

    <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
      <div class="field col-md-8 col-10 mb-3">
        <%= f.label :name, :"ジャンル名" %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class="actions col-md-3 col-4 mb-3">
        <%= f.submit "編集完了", class: "btn btn-success" %>
      </div>
    <% end %>

    <%= link_to admin_genres_path do %>
      <p class="col-md-3 col-4">ジャンル一覧</p>
    <% end %>

  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="row">
  <div class="col-md-10 offset-md-2">

    <%= link_to new_admin_genre_path do %>
      <p>ジャンル作成</p>
    <% end %>

    <h4>ジャンル一覧</h4>

    <table class="genre-table table-bordered table-sm col-md-8 mb-3">
      <thead class="table-info">
        <tr>
          <th>ジャンルID</th>
          <th>ジャンル名</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.id %></td>
            <td><%= genre.name %></td>
            <td>
              <%= link_to edit_admin_genre_path(genre) do %>
                編集する
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/admin/genres/new.html.erb
<div class="row">
  <div class="col-md-10 col-12 offset-md-2">

    <% if @genre.errors.any? %>
      <div class="errors-message mx-auto">
        <%= @genre.errors.count %>件のエラーが発生しました
        <ul>
          <% @genre.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <h4>ジャンル作成フォーム</h4>

    <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
      <div class="field col-md-8 col-10 mb-3">
        <%= f.label :name, :"ジャンル名" %><br>
        <%= f.text_field :name, class: "form-control", placeholder: "ジャンル名を入力してください" %>
      </div>

      <div class="actions col-md-3 col-4 mb-3">
        <%= f.submit "作成する", class: "btn btn-success" %>
      </div>
    <% end %>

    <%= link_to admin_genres_path do %>
      <p class="col-md-3 col-4">ジャンル一覧</p>
    <% end %>

  </div>
</div>

app/views/genres/edit.html.erb
<div class = "row">
  <div class = "col-md-10 offset-md-2">

    <h4>ジャンル編集</h4>

    <%= form_with model: @genre, url: genre_path, method: :patch do |f| %>
      <div class = "field mb-3">
        <%= f.label :"ジャンル名" %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class = "actions mb-3">
        <%= f.submit "作成する", class: "btn btn-success" %>
      </div>
    <% end %>

    <%= link_to genres_path do %>
      <p>ジャンル一覧</p>
    <% end %>

  </div>
</div>

app/views/genres/index.html.erb
<div class = "row">
  <div class = "col-md-10 offset-md-2">

    <%= link_to new_genre_path do %>
      <p>ジャンル作成</p>
    <% end %>

    <h4>ジャンル一覧</h4>

    <table class = "genre-table">
      <thead>
        <tr>
          <th>ジャンルID</th>
          <th>ジャンル名</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td><%= genre.id %></td>
            <td><%= genre.name %></td>
            <td>
              <%= link_to edit_genre_path(genre.id) do %>
                編集する
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/genres/new.html.erb
<div class = "row">
  <div class = "col-md-10 offset-md-2">

    <h4>ジャンル作成フォーム</h4>

    <%= form_with model: @genre, url: genres_path, method: :post do |f| %>
      <div class = "field mb-3">
        <%= f.label :"ジャンル名" %><br>
        <%= f.text_field :name, class: "form-control", placeholder: "ジャンル名を入力してください" %>
      </div>

      <div class = "actions　mb-3">
        <%= f.submit "作成する", class: "btn btn-success" %>
      </div>
    <% end %>

    <%= link_to genres_path do %>
      <p>ジャンル一覧</p>
    <% end %>

  </div>
</div>