config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :areas, except: [:show, :destroy]
    resources :spots, except: [:destroy, :show]
    resources :genres, except: [:show, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end
  scope module: :public do
    devise_for :users
    root to: 'homes#top'
    get "/homes/spot" => "homes#spot"
    post "/homes/guest_sign_in" => "homes#new_guest", as: "guest_sign_in"
    get "/users/withdrawal_confirm" => "users#withdrawal_confirm", as: "withdrawal_confirm"
    resources :users, only: [:show, :edit, :update, :destroy] do
      resource :relationships, only: [:show, :create, :destroy]
    end
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :spots

  validates :name, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :user_id, uniqueness: { scope: :post_id }

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :post_genres
  has_many :genres, through: :post_genres

  validates :name, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :spot
  has_many :post_genres
  has_many :genres, through: :post_genres
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_many_attached :images

  validates :name, presence: true
  validates :user_id, presence: true
  validates :introduction, presence: true
  validates :images, presence: true
  validates :spot_id, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.favorited_order
    self.joins(:favorites).group("favorites.post_id").order("count(favorites.post_id) desc")
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :comment, presence: true

end

app/models/post_genre.rb
class PostGenre < ApplicationRecord

  belongs_to :post
  belongs_to :genre

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :area
  has_many :posts

  validates :name, presence: true
  validates :area_id, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :follower_relationships, foreign_key: :followed_id, class_name: "Relationship"
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :followed_relationships, foreign_key: :follower_id, class_name: "Relationship"
  has_many :followeds, through: :followed_relationships, source: :followed

  has_one_attached :profile_image

  validates :name, presence: true

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "defaullt-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(gravity: :center, resize: "100x100", crop: "70x70+0+0").processed
  end

  def followeds?(user)
    followeds.include?(user)
  end

end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    if @area.save
      flash[:notice] = "You have created area successfully."
      redirect_to areas_path
    else
      render :new
    end
  end

  def index
    @areas = Area.all
  end

  def edit
    @area = Area.find(params[:id])
  end

  def update
    @area = Area.find(params[:id])
    if @area.update(area_params)
      flash[:notice] = "You have updated area successfully."
      redirect_to areas_path
    else
      render :edit
    end
  end

  private

  def area_params
    params.require(:area).permit(:name)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def spot
    @spots = Spot.all
    @spots_json = @spots.map { |o| spot_to_hash(o) }.to_json
  end

  def area
    @areas = Area.all
  end

  def genre
    @genres = Genre.all
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました"
  end

  private

  def spot_to_hash(spot)
    { id: spot.id,
      name: spot.name,
      lat: spot.latitude,
      lng: spot.longitude }
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		@post.user_id = current_user.id
		if @post.save
			flash[:notice] = "You have created post successfully."
			redirect_to post_path(@post)
		else
			render :new
		end
	end

	def index
		@posts = Post.all.includes(:post_genres, :spot)
		@spots = Spot.all
		@genres = Genre.all
		@posts = @posts.where("spot.area_id": params[:area_id]) if params[:area_id].present?
		@posts = @posts.where(spot_id: params[:spot_id]) if params[:spot_id].present?
		@posts = @posts.where("post_genres.genre_id": params[:genre_id]) if params[:genre_id].present?
		@posts = @posts.where("name or introduction like ?", "%#{params[:name]}%") if params[:name].present?
		@posts = @posts.favorited_order if params[:favorites].present?
	end

	def show
		@post = Post.find(params[:id])
		@post_comment = PostComment.new
		@post_json = post_to_hash(@post).to_json
	end

	def edit
		@post = Post.find(params[:id])
		unless @post.user == current_user
			redirect_to post_path(params[:id])
		end
	end

	def update
		@post = Post.find(params[:id])
		if @post.update(post_params)
			flash[:notice] = "You have updated post successfully."
			redirect_to post_path(@post)
		else
			render :edit
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:name, :introduction, :spot_id, :image, :address, :latitude, :longitude, genre_ids: [])
	end

	def post_to_hash(post)
    { id: post.id,
      name: post.name,
      lat: post.latitude,
      lng: post.longitude }
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_genres_helper.rb
module PostGenresHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_index.html.erb
<div class = "d-flex justify-content-center flex-wrap">
  <% posts.each do |post| %>
    <div class = "col-4">
      <%= link_to post_path(post.id) do %>
        <table class = "post-table">
          <tr>
            <th>店名：<%= post.name %></th>
          </tr>
          <tr>
            <td><%= image_tag post.get_post_image(300,300) %></td>
          </tr>
        </table>
      <% end %>
      <p>いいね！<%= post.favorites.count %>件</p>
    </div>
  <% end %>
</div>

app/views/posts/_list.html.erb
<div class = "d-flex justify-content-center flex-wrap col-md-8 mx-auto">
  <% posts.each do |post| %>
    <div class = "col-4 mx-auto">
      <%= link_to post_path(post.id) do %>
        <table class = "post-table">
          <tr>
            <th>店名：<%= post.name %></th>
          </tr>
          <tr>
            <td><%= image_tag post.get_post_image(300,300) %></td>
          </tr>
        </table>
      <% end %>
      <p>いいね！<%= post.favorites.count %>件</p>
    </div>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class = "row justify-content-center">
  <div class = "col-8">

    <h4>投稿を編集する</h4>

    <%= form_with model: @post, url: post_path, method: :patch do |f| %>
      <div class = "field mb-3">
        <%= f.label :"タイトル" %><br>
        <%= f.text_field :name, class: "form-control" %>
      </div>

      <div class = "field mb-3">
        <%= f.label :"紹介文" %><br>
        <%= f.text_field :introduction, class: "form-control" %>
      </div>

      <div class = "field mb-3">
        <%= f.label :"画像" %><br>
        <%= f.file_field :image, accept: "image/*" %>
      </div>

      <div class = "selection mb-3">
        <%= f.label :"スポット選択" %><br>
        <%= f.collection_select :spot_id, Spot.all, :id, :name %>
      </div>

      <div class = "collection mb-3">
        <%= f.label :"ジャンル選択(複数選択可)" %><br>
        <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name, include_hidden: false) do |b| %>
          <%= b.label { b.check_box + b.text } %>
        <% end %>
      </div>

      <div data-controller = "google-map--form">
        <%= f.label :"キーワードで探す" %><br>
        <%= f.search_field :keyword, data: { google_map__form_target: "keyword" } %><br>

        <%= f.label :"緯度" %>
        <%= f.number_field :latitude, data: { google_map__form_target: "latitude" }, tabindex: -1, readonly: true, class: "looks_disable" %>
        <%= f.label :"経度" %>
        <%= f.number_field :longitude, data: { google_map__form_target: "longitude" }, tabindex: -1, readonly: true, class: "looks_disable"%><br>

        <div data-google-map--form-target="map" style="height:30vh;max-width:300px;"></div>

        <%= f.label :"address" %>
        <%= f.text_field :address, list: "address_list", data: { google_map__form_target: "address" } %><br>
        <datalist id = "address_list" data-google-map--form-target = "addressList" ></datalist>
      </div>

      <div class = "actions mb-3">
        <%= f.submit "編集完了", class: "btn btn-success" %>
      </div>
    <% end %>

    <%= link_to post_path(@post.id) do %>
      戻る
    <% end %>
    <%= link_to post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
      削除する
    <% end %>

  </div>
</div>

app/views/posts/index.html.erb
<div class = "row">

  <div class = "col-2">
    <%= render 'users/sidebar' %>
  </div>

  <div class = "col-10">
    <h3 class = "row justify-content-center mb-3">投稿一覧</h3>

    <div class = "row mb-3">
      <%= form_with url: posts_path, method: :get, local: true do |f| %>
        <div class = "field col-10 mb-1">
          <%= f.label :"スポットで絞り込む"%><br>
          <%= f.collection_select :spot_id, @spots, :id, :name, { selected: params[:spot_id], include_blank: "選んで下さい" }, { class: "form-control" } %>
        </div>

        <div class = "field col-10 mb-1">
          <%= f.label :"ジャンルで絞り込む"%><br>
          <%= f.collection_select :genre_id, @genres, :id, :name, { selected: params[:genre_id], include_blank: "選んで下さい" }, { class: "form-control" } %>
        </div>

        <div class = "serch-field col-10 mb-1">
          <%= f.label :"キーワード検索" %><br>
          <%= f.search_field :name, value: params[:name], class: "form-control me-2", placeholder: "Search" %>
        </div>

        <div class = "actions col-8 mb-1">
          <%= f.submit "Search", class: "btn btn-outline-success" %>
        </div>
        <% end %>
    </div>

    <div class = "row mb-3">
      <%= link_to posts_path(favorites: "favorite"), "data-turbolinks": false do %>
        人気の投稿
      <% end %>
    </div>

    <%= render 'list', posts: @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class = "row justify-content-center">
  <div class = "col-8">

    <h4>投稿フォーム</h4>

    <%= form_with model: @post, url: posts_path, method: :post do |f| %>
      <div class = "field mb-3">
        <%= f.label :"タイトル" %><br>
        <%= f.text_field :name, class: "form-control", placeholder: "お店の名前を入れてください" %>
      </div>

      <div class = "field mb-3">
        <%= f.label :"紹介文" %><br>
        <%= f.text_field :introduction, class: "form-control", placeholder: "お店の感想・お勧めのメニューなど教えてください" %>
      </div>

      <div class = "field mb-3">
        <%= f.label :"画像" %><br>
        <%= f.file_field :image, accept: "image/*" %>
      </div>

      <div class = "selection mb-3">
        <%= f.label :"スポット選択" %><br>
        <%= f.collection_select :spot_id, Spot.all, :id, :name, include_blank: "選択して下さい" %>
      </div>

      <div class = "collection mb-3">
        <%= f.label :"ジャンル選択(複数選択可)" %><br>
        <%= f.collection_check_boxes(:genre_ids, Genre.all, :id, :name, include_hidden: false) do |b| %>
          <%= b.label { b.check_box + b.text } %>
        <% end %>
      </div>

      <div data-controller = "google-map--form">
        <%= f.label :"キーワードで探す" %><br>
        <%= f.search_field :keyword, data: { google_map__form_target: "keyword" } %><br>

        <%= f.label :"緯度" %>
        <%= f.number_field :latitude, data: { google_map__form_target: "latitude" }, tabindex: -1, readonly: true, class: "looks_disable" %>
        <%= f.label :"経度" %>
        <%= f.number_field :longitude, data: { google_map__form_target: "longitude" }, tabindex: -1, readonly: true, class: "looks_disable"%><br>

        <div data-google-map--form-target="map" style="height:30vh;max-width:300px;"></div>

        <%= f.label :"address" %>
        <%= f.text_field :address, list: "address_list", data: { google_map__form_target: "address" } %><br>
        <datalist id = "address_list" data-google-map--form-target = "addressList" ></datalist>
      </div>

      <div class = "actions mb-3">
        <%= f.submit "投稿する", class: "btn btn-success" %>
      </div>
    <% end %>

  </div>
</div>

app/views/posts/show.html.erb
<div class = "row">
  <div class = "col-md-8 offset-md-2">
    <div class = "card mb-3">
      <%= image_tag 'hiroshima.jpg', size:"700x700", class:"card-img" %>
      <div class = "card-img-overlay">
        <div class = "post-user d-flex offset-md-2 mb-1">
          <div class = "col-2">
            <%= image_tag @post.user.get_profile_image, class: "rounded-circle" %>
          </div>
          <table class = "col-4">
            <tr>
              <td><%= @post.user.name %></td>
            </tr>
            <tr>
              <td>店名：<%= @post.name %></td>
            </tr>
            <tr>
              <td>スポット：<%= @post.spot.name %></td>
            </tr>
          </table>
          <% if @post.user == current_user %>
            <div class = "col-3 mx-auto">
              <%= link_to edit_post_path(@post.id) do %>
                <i class="fas fa-user-cog"></i>投稿編集<br>
              <% end %>
              <%= link_to post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？" do %>
                <i class="fa-solid fa-trash"></i>投稿削除
              <% end %>
            </div>
          <% end %>
        </div>
        <div class = "post-detail offset-md-2">
          <div class = "card-img-top"><%= image_tag @post.get_post_image(500,500), class: "img-fluid" %></div>
            <div class = "d-flex">
              <% if @post.favorited_by?(current_user) %>
                <p>
                  <%= link_to post_favorite_path(@post), method: :delete do %>
                    <i class="fa-solid fa-heart"></i>
                  <% end %>
                  いいね！<%= @post.favorites.count %>件
                </p>
              <% else %>
                <p>
                  <%= link_to post_favorite_path(@post), method: :post do %>
                    <i class="fa-regular fa-heart"></i>
                  <% end %>
                  いいね！<%= @post.favorites.count %>件
                </p>
              <% end %>
              <p class = "ml-md-5"><%= @post.created_at.strftime('%Y/%m/%d') %></p>
            </div>
            <p><%= @post.introduction %></p>
            <% @post.genres.each do |genre| %>
              #<%= genre.name %>
            <% end %>
          </div>
        </div>
      </div>

    <div data-controller="google-map--show">
      <p>住所：<%= @post.address %></p>
      <div data-google-map--show-target="map" data-json="<%= @post_json %>" style="height:30vh;max-width:50%;"></div>
    </div>
    <div class = "post-comment mt-3">
      <p>コメント件数：<%= @post.post_comments.count %></p>
      <% @post.post_comments.each do |post_comment| %>
        <div class = "post-comment-detail d-flex mb-1">
          <p class = "mr-3"><%= image_tag post_comment.user.get_profile_image, class: "rounded-circle" %></p>
          <p><%= post_comment.user.name %>　<%= post_comment.created_at.strftime('%Y/%m/%d') %><br>
          <%= post_comment.comment %></p>
          <% if post_comment.user == current_user %>
            <p class = "ml-2">
              <%= link_to post_post_comment_path(post_comment.post, post_comment), method: :delete do %>
                <br><i class="fa-solid fa-trash"></i>
              <% end %>
            </p>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class = "post-comment-field">
      <%= form_with(model: [@post, @post_comment]) do |f| %>
        <%= f.text_area :comment, placeholder: "コメントをここに" %>
        <%= f.submit "送信する", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>