config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: "admin/sessions"
  }
  namespace :admin do
    resources :users, only: [:index, :destroy]
    resources :areas, except: [:show, :destroy]
    resources :spots, except: [:destroy, :show]
    resources :genres, except: [:show, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end
  scope module: :public do
    devise_for :users
    root to: 'homes#top'
    get "/homes/spot" => "homes#spot"
    post "/homes/guest_sign_in" => "homes#new_guest", as: "guest_sign_in"
    get "/users/withdrawal_confirm" => "users#withdrawal_confirm", as: "withdrawal_confirm"
    resources :users, only: [:show, :edit, :update, :destroy] do
      resource :relationships, only: [:show, :create, :destroy]
    end
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :spots

  validates :name, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :user_id, uniqueness: { scope: :post_id }

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :post_genres
  has_many :genres, through: :post_genres

  validates :name, presence: true

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :spot
  has_many :post_genres
  has_many :genres, through: :post_genres
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  has_many_attached :images

  validates :name, presence: true
  validates :user_id, presence: true
  validates :introduction, presence: true
  validates :images, presence: true
  validates :spot_id, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.favorited_order
    self.joins(:favorites).group("favorites.post_id").order("count(favorites.post_id) desc")
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :comment, presence: true

end

app/models/post_genre.rb
class PostGenre < ApplicationRecord

  belongs_to :post
  belongs_to :genre

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :area
  has_many :posts

  validates :name, presence: true
  validates :area_id, presence: true
  validates :address, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :follower_relationships, foreign_key: :followed_id, class_name: "Relationship"
  has_many :followers, through: :follower_relationships, source: :follower
  has_many :followed_relationships, foreign_key: :follower_id, class_name: "Relationship"
  has_many :followeds, through: :followed_relationships, source: :followed

  has_one_attached :profile_image

  validates :name, presence: true

  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/no_image.jpg")
      profile_image.attach(io: File.open(file_path), filename: "defaullt-image.jpg", content_type: "image/jpeg")
    end
    profile_image.variant(gravity: :center, resize: "100x100", crop: "70x70+0+0").processed
  end

  def followeds?(user)
    followeds.include?(user)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout "admin"
  before_action :authenticate_admin!

  def index
    @users = User.all
    @users = @users.where("name like ?", "%#{params[:name]}%") if params[:name].present?
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path, notice: "ユーザーを削除しました。"
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def new
    @area = Area.new
  end

  def create
    @area = Area.new(area_params)
    if @area.save
      flash[:notice] = "You have created area successfully."
      redirect_to areas_path
    else
      render :new
    end
  end

  def index
    @areas = Area.all
  end

  def edit
    @area = Area.find(params[:id])
  end

  def update
    @area = Area.find(params[:id])
    if @area.update(area_params)
      flash[:notice] = "You have updated area successfully."
      redirect_to areas_path
    else
      render :edit
    end
  end

  private

  def area_params
    params.require(:area).permit(:name)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def spot
    @spots = Spot.all
    @spots_json = @spots.map { |o| spot_to_hash(o) }.to_json
  end

  def area
    @areas = Area.all
  end

  def genre
    @genres = Genre.all
  end

  def new_guest
    user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
    sign_in user
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました"
  end

  private

  def spot_to_hash(spot)
    { id: spot.id,
      name: spot.name,
      lat: spot.latitude,
      lng: spot.longitude }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @posts = @posts.includes(:favorites).where("favorites.user_id": params[:favorites]) if params[:favorites].present?
    if @user.email == 'guest@example.com'
      redirect_to root_path
    end
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
    if current_user.email == 'guest@example.com'
      redirect_to root_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def withdrawal_confirm
    @user = User.find(current_user)
    if current_user.email == 'guest@example.com'
      redirect_to root_path
    end
  end

  def destroy
    user = User.find(current_user)
    user.destroy
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_genres_helper.rb
module PostGenresHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<div class="row">
  <div class="col-md-10 col-12 mx-md-auto">

    <h4 class="my-3">ユーザー一覧</h4>

    <%= form_with url: admin_users_path, method: :get, local: true do |f| %>
      <div class="serch-field col-md-6 col-10 mb-1">
        <%= f.label :name, :"ユーザー検索" %><br>
        <%= f.search_field :name, value: params[:name], class: "form-control me-2", placeholder: "ユーザー名で探す" %>
      </div>

      <div class="actions col-md-5 col-3 mb-3">
        <%= f.submit "Search", class: "btn btn-outline-success" %>
      </div>
    <% end %>

    <table class="spot-table table-bordered table-sm col-md-8 col-12 mb-3">
      <thead class="table-info">
        <tr>
          <th>ユーザーID</th>
          <th>ユーザー名</th>
          <th>メールアドレス</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= link_to "退会させる", admin_user_path(user), method: :delete, "data-confirm" => "本当に退会させますか？" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div

app/views/users/_info.html.erb
<div class = "d-flex justify-content-center mb-3">
  <div class = "col-md-1">
    <%= image_tag user.get_profile_image, class: "rounded-circle" %>
  </div>
  <table class = "col-2">
    <tr>
      <th>name：</th>
      <th><%= user.name %></th>
      <th></th>
    </tr>
    <tr>
      <th>投稿：</th>
      <th><%= user.posts.count %></th>
    </tr>
  </table>
</div>

<div class = "d-flex justify-content-center col-md-8 mx-auto mb-3">
  <div class = "col-3 mx-1">
    <%= link_to user_path(user), "data-turbolinks": false do %>
      投稿一覧
    <% end %>
  </div>
  <div class = "col-3 mx-1">
    <%= link_to user_path(user, favorites: user.id), "data-turbolinks": false do %>
      いいね！一覧
    <% end %>
  </div>
  <% if @user.id == current_user.id %>
    <div class = "col-3 mx-1">
      <%= link_to edit_user_path(user) do %>
        会員情報編集
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/_sidebar.html.erb
<h3>User info</h3>
<div>
  <%= image_tag current_user.get_profile_image %><br>
  <%= current_user.name %>
</div>

<div class = "user-edit-link mb-3">
  <%= link_to edit_user_path(current_user), class: "btn btn-outline-secondary btn-block" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>

<div>
  <%= link_to new_post_path, class: "btn btn-outline-secondary btn-block" do %>
    投稿する
  <% end %>
</div>

app/views/users/edit.html.erb
<div class = "row justify-content-center">
  <div class = "col-8">
    <h4>会員情報編集</h4>

    <%= form_with model: @user do |f| %>
      <div class = "field mb-3" >
        <%= f.label :Name %><br>
        <%= f.text_field :name, class: "form-control", autofocus: true %>
      </div>

      <div class = "field mb-3" >
        <%= f.label :"プロフィール画像" %><br>
        <%= f.file_field :profile_image %>
      </div>

      <div class = "actions mb-3" >
        <%= f.submit "編集完了", class: "btn btn-success" %>
      </div>
    <% end %>

    <div class = "withdrawl" >
      <%= link_to withdrawal_confirm_path do %>
        退会手続き
      <% end %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<h3 class = "row justify-content-center mb-3">Users info</h3>

<%= render 'info', user: @user %>

<%= render 'posts/list', posts: @posts %>

app/views/users/withdrawal_confirm.html.erb
<div class = "row justify-content-center">
  <div class = "col-8">
    <h4>退会手続き</h4>
    <p>退会手続きにより投稿した内容も削除されます。<br>
    本当に退会しますか？</p>
    <p>
      <%= link_to user_path(current_user.id), method: :delete, "data-confirm" => "本当に退会しますか？" do %>
        退会する
      <% end %>
    </p>
  </div>
</div>